name: k3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - notebook>5.2
  - jupyterlab>1.1
  - ipywidgets
  - pandas
  - scipy
  - numba
  - scikit-image
  - vtk
  - pip:
     - k3d
     - nibabel
